project:
  type: website
  resources: static/*
  output-dir: ../_site

website:
  title: "ECHILD"
  image: "android-chrome-512x512.png"
  favicon: "favicon.ico"
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/UCL-ARC-Workshops/202401-echild-workshop
  page-navigation: true
  search: true
  back-to-top-navigation: true
  page-footer:
    center:
      - text: "License"
        href: license.qmd
  navbar:
    title: "is travelling"
    background: dark
    logo: echild.png
    logo-alt: "ECHILD logo."
    collapse-below: lg

format:
  html:
    toc: false
    theme: sandstone
    css: styles.css
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
